/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Car Dealership Backend
 * API para a Car Dealership
 * OpenAPI spec version: 0.0.1
 */
export type Get200 = {
  Car_Dealership_API: string;
};

export type PostUsersBody = {
  /** @minLength 2 */
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @minLength 6 */
  password: string;
};

export type PostUsers201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  email: string;
  createdAt: string;
  updatedAt: string;
};

export type PostUsers409 = {
  message: string;
};

export type GetUsersParams = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
};

export type GetUsers200User = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  email: string;
  createdAt: string;
  updatedAt: string;
};

export type GetUsers200CarsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  brand: string;
  model: string;
  /** @nullable */
  version: string | null;
  year: number;
  price: string;
  /** @nullable */
  fuel: string | null;
  /** @nullable */
  transmission: string | null;
  /** @nullable */
  mileage: number | null;
  /** @nullable */
  imageUrl: string | null;
  createdAt: string;
  updatedAt: string;
};

export type GetUsers200Meta = {
  page: number;
  perPage: number;
  total: number;
  totalPages: number;
};

export type GetUsers200 = {
  user: GetUsers200User;
  cars: GetUsers200CarsItem[];
  meta: GetUsers200Meta;
};

export type GetUsers404 = {
  message: string;
};

export type PatchUsersBody = {
  /** @minLength 2 */
  name?: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email?: string;
  /** @minLength 6 */
  currentPassword?: string;
  /** @minLength 6 */
  newPassword?: string;
};

export type PatchUsers200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  email: string;
  createdAt: string;
  updatedAt: string;
};

export type PatchUsers404 = {
  message: string;
};

export type PatchUsers409 = {
  message: string;
};

/**
 * Usuário deletado com sucesso
 * @nullable
 */
export type DeleteUsers204 = typeof DeleteUsers204[keyof typeof DeleteUsers204] | null;


export const DeleteUsers204 = {
} as const;

export type DeleteUsers404 = {
  message: string;
};

export type PostUsersLoginBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @minLength 6 */
  password: string;
};

export type PostUsersLogin200 = {
  token: string;
};

export type PostUsersLogin401 = {
  message: string;
};

export type GetCarsSearchParams = {
/**
 * @minLength 1
 */
search: string;
};

export type GetCarsSearch200CarsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  brand: string;
  model: string;
  /** @nullable */
  version: string | null;
  year: number;
  price: string;
  /** @nullable */
  fuel: string | null;
  /** @nullable */
  transmission: string | null;
  /** @nullable */
  mileage: number | null;
  /** @nullable */
  imageUrl: string | null;
  createdAt: string;
  updatedAt: string;
};

export type GetCarsSearch200 = {
  cars: GetCarsSearch200CarsItem[];
  reply: string;
};

export type GetCarsParams = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
};

export type GetCars200CarsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  brand: string;
  model: string;
  /** @nullable */
  version: string | null;
  year: number;
  price: string;
  /** @nullable */
  fuel: string | null;
  /** @nullable */
  transmission: string | null;
  /** @nullable */
  mileage: number | null;
  /** @nullable */
  imageUrl: string | null;
  createdAt: string;
  updatedAt: string;
};

export type GetCars200Meta = {
  page: number;
  perPage: number;
  total: number;
  totalPages: number;
};

export type GetCars200 = {
  cars: GetCars200CarsItem[];
  meta: GetCars200Meta;
};

export type PostCarsBody = {
  /** @minLength 1 */
  brand: string;
  /** @minLength 1 */
  model: string;
  version?: string;
  /**
     * @minimum 1900
     * @maximum 9007199254740991
     */
  year: number;
  price: string;
  fuel?: string;
  transmission?: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  mileage?: number;
  imageUrl?: string;
};

export type PostCars201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  brand: string;
  model: string;
  /** @nullable */
  version: string | null;
  year: number;
  price: string;
  /** @nullable */
  fuel: string | null;
  /** @nullable */
  transmission: string | null;
  /** @nullable */
  mileage: number | null;
  /** @nullable */
  imageUrl: string | null;
  createdAt: string;
  updatedAt: string;
};

export type GetCarsId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  brand: string;
  model: string;
  /** @nullable */
  version: string | null;
  year: number;
  price: string;
  /** @nullable */
  fuel: string | null;
  /** @nullable */
  transmission: string | null;
  /** @nullable */
  mileage: number | null;
  /** @nullable */
  imageUrl: string | null;
  createdAt: string;
  updatedAt: string;
};

export type GetCarsId404 = {
  message: string;
};

export type PatchCarsIdBody = {
  /** @minLength 1 */
  brand?: string;
  /** @minLength 1 */
  model?: string;
  version?: string;
  /**
     * @minimum 1900
     * @maximum 9007199254740991
     */
  year?: number;
  price?: string;
  fuel?: string;
  transmission?: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  mileage?: number;
  imageUrl?: string;
};

export type PatchCarsId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  brand: string;
  model: string;
  /** @nullable */
  version: string | null;
  year: number;
  price: string;
  /** @nullable */
  fuel: string | null;
  /** @nullable */
  transmission: string | null;
  /** @nullable */
  mileage: number | null;
  /** @nullable */
  imageUrl: string | null;
  createdAt: string;
  updatedAt: string;
};

export type PatchCarsId404 = {
  message: string;
};

/**
 * Carro deletado com sucesso
 * @nullable
 */
export type DeleteCarsId204 = typeof DeleteCarsId204[keyof typeof DeleteCarsId204] | null;


export const DeleteCarsId204 = {
} as const;

export type DeleteCarsId404 = {
  message: string;
};

/**
 * Retorna um link para a documentação da API.
 * @summary Rota padrão
 */
export const getGetUrl = () => {




  return `http://localhost:3333/`
}

export const get = async ( options?: RequestInit): Promise<Get200> => {

  const res = await fetch(getGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: Get200 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Cria uma nova conta com nome, email e senha.
 * @summary Cadastrar usuário
 */
export const getPostUsersUrl = () => {




  return `http://localhost:3333/users`
}

export const postUsers = async (postUsersBody: PostUsersBody, options?: RequestInit): Promise<PostUsers201> => {

  const res = await fetch(getPostUsersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postUsersBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: PostUsers201 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Retorna o perfil do usuário autenticado e seus carros paginados.
 * @summary Obter perfil
 */
export const getGetUsersUrl = (params?: GetUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3333/users?${stringifiedParams}` : `http://localhost:3333/users`
}

export const getUsers = async (params?: GetUsersParams, options?: RequestInit): Promise<GetUsers200> => {

  const res = await fetch(getGetUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetUsers200 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Atualiza nome, email ou senha do usuário autenticado.
 * @summary Atualizar perfil
 */
export const getPatchUsersUrl = () => {




  return `http://localhost:3333/users`
}

export const patchUsers = async (patchUsersBody: PatchUsersBody, options?: RequestInit): Promise<PatchUsers200> => {

  const res = await fetch(getPatchUsersUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchUsersBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: PatchUsers200 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Remove a conta do usuário autenticado e seus carros.
 * @summary Excluir conta
 */
export const getDeleteUsersUrl = () => {




  return `http://localhost:3333/users`
}

export const deleteUsers = async ( options?: RequestInit): Promise<DeleteUsers204> => {

  const res = await fetch(getDeleteUsersUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: DeleteUsers204 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Autentica o usuário e retorna um token JWT.
 * @summary Login
 */
export const getPostUsersLoginUrl = () => {




  return `http://localhost:3333/users/login`
}

export const postUsersLogin = async (postUsersLoginBody: PostUsersLoginBody, options?: RequestInit): Promise<PostUsersLogin200> => {

  const res = await fetch(getPostUsersLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postUsersLoginBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: PostUsersLogin200 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Interpreta a busca com IA e retorna carros relevantes.
 * @summary Buscar carros por texto (IA)
 */
export const getGetCarsSearchUrl = (params: GetCarsSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3333/cars/search?${stringifiedParams}` : `http://localhost:3333/cars/search`
}

export const getCarsSearch = async (params: GetCarsSearchParams, options?: RequestInit): Promise<GetCarsSearch200> => {

  const res = await fetch(getGetCarsSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetCarsSearch200 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Retorna todos os carros com paginação.
 * @summary Listar carros
 */
export const getGetCarsUrl = (params?: GetCarsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3333/cars?${stringifiedParams}` : `http://localhost:3333/cars`
}

export const getCars = async (params?: GetCarsParams, options?: RequestInit): Promise<GetCars200> => {

  const res = await fetch(getGetCarsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetCars200 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Cadastra um novo carro para o usuário autenticado.
 * @summary Cadastrar carro
 */
export const getPostCarsUrl = () => {




  return `http://localhost:3333/cars`
}

export const postCars = async (postCarsBody: PostCarsBody, options?: RequestInit): Promise<PostCars201> => {

  const res = await fetch(getPostCarsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postCarsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: PostCars201 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Retorna os detalhes de um carro específico.
 * @summary Obter carro por ID
 */
export const getGetCarsIdUrl = (id: string,) => {




  return `http://localhost:3333/cars/${id}`
}

export const getCarsId = async (id: string, options?: RequestInit): Promise<GetCarsId200> => {

  const res = await fetch(getGetCarsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetCarsId200 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Atualiza os dados de um carro do usuário autenticado.
 * @summary Atualizar carro
 */
export const getPatchCarsIdUrl = (id: string,) => {




  return `http://localhost:3333/cars/${id}`
}

export const patchCarsId = async (id: string,
    patchCarsIdBody: PatchCarsIdBody, options?: RequestInit): Promise<PatchCarsId200> => {

  const res = await fetch(getPatchCarsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchCarsIdBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: PatchCarsId200 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Remove um carro do usuário autenticado.
 * @summary Excluir carro
 */
export const getDeleteCarsIdUrl = (id: string,) => {




  return `http://localhost:3333/cars/${id}`
}

export const deleteCarsId = async (id: string, options?: RequestInit): Promise<DeleteCarsId204> => {

  const res = await fetch(getDeleteCarsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: DeleteCarsId204 = body ? JSON.parse(body) : {}
  return data
}
